# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f31b76e301c3af0116cfd80488a376fa59551f0a80f84542597abf610899cac664d2764b338e9ce9a94e28c17a25a25282f0c0e965184a2ad6fc8e57abb31aa0

test:
  secret_key_base: 95056fb6ea0722ddd7fcdff8e98613ff856575044617d7ebacdea64de4f61ca9519284c0280f02df8964e673ac0d4865afccbd50727581698daf18e0cd83a4f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
